# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 789fe957a4a3bee5a396677a2c05cc20472c0f7840a539a12c4813ac83b9428c04cd2cd53c78f6a8544b0ad8cecde701c2e014e4b77b59d1afc6b7421df4affc

test:
  secret_key_base: fe0dd09ee28b4af15915e1b298852134609b96b9b6034ff389a403e413b7ffa4de41e6a35508f598a60e9f25369982fdacf094b6d3f563d1a620b0e1c3edd296

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
